; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino, espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
board_build.embed_txtfiles = 
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
	managed_components/espressif__esp_insights/server_certs/https_server.crt
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-I lib/LEDs
	-I lib/Gyro
	-I lib/DisplayMode
	-I lib/DisplayGlobals
	-I lib/DisplayDraw
	-I lib/VoiceRecognition
	-I lib/VoiceCommands
	-I lib/ServeurSetup
	-I lib/ServeurRequetes
	-I"C:/Users/mimil/.platformio/packages/framework-espidf/components/esp-sr/include"
	-I"C:/Users/mimil/.platformio/packages/framework-espidf/components/esp-afe-sr/include"
	-I"C:/Users/mimil/.platformio/packages/framework-espidf/components/esp-mn/include"
	-I .pio/build/esp32-s3-devkitc1-n16r8
	-O1
    -fno-tree-vectorize
	
lib_deps = 
	https://github.com/ESP32Async/ESPAsyncWebServer
    https://github.com/ESP32Async/AsyncTCP
	fastled/FastLED@^3.10.3
	electroniccats/MPU6050@^1.4.4

; Script extra pour déplacer automatiquement les modèles vocaux avant upload
extra_scripts = pre:pio_extra_movemodel.py

